project:
  type: website

website:
  title: "Physics Data Playground"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview
      - text: Game
        menu: 
          - href: Delivery.qmd
            text: "Using the Game"
          - href: Gameplay.qmd
            text: "Playing the game"
          - href: LevelEditor.qmd
            text: "Level Editor"
          - href: IncentiveStore.qmd
            text: "Incentives and Store"
          - href: AllLevels.qmd
            text: "All game levels"
      - text: "Supports"
        menu:
          - href: CognitiveSupports.qmd
            text: "Cognitive Supports"
          - href: AffectiveSupports.qmd
            text: "Affective Supports"
      - text: "Internal Assessment"
        menu: 
          - href: CompetencyModel.qmd
            text: "Competency Model"
          - href: EvidenceModels.qmd
            text: "Evidence Models"
          - href: EvidenceIdentification.qmd
            text: "Evidence Identification"
          - href: Statistics.qmd
            text: "Statistics Reported by the Bayes net"
          - href: QMatrix.qmd
            text: "Q Matrix"
      - text: Instruments
        menu:
        - href: preposttest.qmd
          text: "Pre/Post test"
        - href: IMI.qmd
          text: "Intrinsic Motivation Inventory"
        - href: PA.qmd
          text: "Physics Animations"
      - text: "Protocols"
        menu:
        - href: Before-After.qmd
          text: "Support Timing Study"
        - href: SupportEfficacy.qmd
          text: "Support Efficacy Study"
      - text: "Data"
        menu:
        - href: Codebook.qmd
          text: Codebook
        - href: BAdata.qmd
          text: "Support Timing Data"
        - href: EfficacyData.qmd
          text: "Support Efficacy Data"
        - href: Events.qmd
          text: "Log files"
      - href: Analyses.qmd
        text: "Analysis Scripts"
      - text: Software
        menu: 
          - href: GameEngine.qmd
            text: "Game Engine"
          - href: Peanut.qmd
            text: "Peanut Bayes Net Engine"
          - href: Proc4.qmd
            text: "Proc4 scoring system"
      - href: Personnel.qmd
        text: "Personnel"
      - href: Articles.qmd
        text: "Articles"
      - text: "Bibliography"
        menu:
          - href: papers.qmd
            text: "Project Papers"
          - href: bib.qmd
            text: "References"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

margin-header: |
  ![Physics Playground Logo](/img/PP-Website-BG.jpg)

bibliography:  PPReferences.bib
csl:  apa.csl


