---
title: "Codebook"
---

## IDs

`StudyID`
: Main study ID and primary key.  First letter is study condition.

`ID1`, `ID2`
: Internal game IDs, first letter (following the 3 digits) is study condition.


## Study Conditions _Ginny_

The study was divided into two intervention/data collection periods, and the content into
two topics:  `ECT` -- Evidence Can Transfer, and `POT` -- Properties of Torque.

`Topic1`
: Which topic was addressed in the first study period (and the first (mid) posttest).  One of `ECT`, `POT`.

`Topic2`
: Which topic was addressed in the second study period (and the final posttest).

`Condition`
: One of `A`, `B`, `C`, `D`, `E`, or `F` giving the study condition (see [protocl](SupportEfficacy.qmd)

`CognitiveSupport`
: Did the student have access to cognitive supports?  (Logical)

`AffectiveECT` 
: Did the student have access to affective supports during the period in which `ECT`
was the topic

`AffectivePOT`
: Did the student have access to affective supports during the period in which `POT`
was the topic

The following table summarizes the relationship between these treatment values.

Condition | Midtest | Posttest | CognitiveSupports | AffectiveECD | AffectivePOT
--------- | ------- | -------- | ----------------- | ------------ | ------------
 A        | ECT     | POT      | TRUE              | FALSE        | TRUE
 B        | POT     | ECT      | TRUE              | TRUE         | FALSE
 C        | ECT     | POT      | TRUE              | TRUE         | FALSE
 D        | POT     | ECT      | TRUE              | FALSE        | TRUE
 E        | POT     | ECT      | FALSE             | FALSE        | FALSE
 F        | ECT     | POT      | FALSE             | FALSE        | FALSE


## Demographic Varibles



`Age`
: Self-reported age in years.

`Sex`, `Gender`
: Self-reported gender

The race/ethnicity question was a check all that applied.  Respondents may have 
chosen more than one category.

`American Indian or Alaskan Native`, `Asian`, `Black or African American`, `Hispanic`, `Hawaiian or Pacific Islander`, `White`, `Other (enter)`, `Prefer not to say`
: Logical value giving selected race/ethnicity

`Other_TEXT`
: Text string entered for "Other".

`Ethnicity`
: If single option was selected, that option.  If multiple options selected, then `Mixed`.

`Gaming`
: "How often do you play video games?"  Ordinal, possible values:   
`Never`,	`Once a month or less`,	`Once a week`,	`3-4 times a week`,	`Every day`

`Physics`
: "Have you studied Physics?" Possible answers `Yes`, `No`.

## Pretest/Post-test 

Question texts and key are available [here](preposttest.qmd).  The `-` has been 
replaced with `_`.  

Posttest results have a suffix of `.ect` or `.pot` (note these two posttests were
given of different days).

### Pretest Raw Scores

`Progress`
: Completion percentage for prettest questionnaire

`Duration`
: Length of time (in seconds) needed to complete pretest questionnaire including
demographic items

`Finished`
: Did Qualtrics consider the pretest questionnaire finished.

`RecordedDate`
: Date pretest questionnaire was collected

`A_NQ1` through `A_NQ8`
: Pretest responses to near transfer ECT questions, raw responses (note: available 
with either the original option text or "A","B","C","D" coded options)

`A_NQ8` through `A_NQ14`
: Pretest responses to near transfer POT questions, raw responses 
(either original options or A,B,C coding)

`A_FQ1` through `A_FQ8`
: Pretest responses to far transfer ECT questions, raw responses
(either original options or A,B,C coding)

`A_FQ8` through `A_FQ14`
(either original options or A,B,C coding)
: Pretest responses to far transfer POT questions, raw responses

`SC0`
: Prestest score as computed by Qualtrics

`A_NQ1_scored` through `A_NQ8_scored`
: Pretest scored (0,1) responses to near transfer ECT questions, raw responses

`A_NQ8_scored` through `A_NQ14_scored`
: Pretest scored (0,1) responses to near transfer POT questions, raw responses

`A_FQ1_scored` through `A_FQ8_scored`
: Pretest scored (0,1) responses to far transfer ECT questions, raw responses

`A_FQ8_scored` through `A_FQ14_scored`
: Pretest scored (0,1) responses to far transfer POT questions, raw responses

`NearECT`, `FarECT`, `NearPOT`, `FarPOT`
: Pretest sum of scored responses in that categories.

`Near`, `Far`
: `Near = NearECT + NearPOT`, `Far = FarECT + FarPOT`.  Note these are not
available for the posttest because it would require adding across administrations on 
different days.  

`ECT`, `POT`
: `ECT = NearECT + FarECT`, `POT = NearPOT + FarPOT`

`PhysicsScore`
: `PhysicsScore = ECT + POT`.  Again not available for posttest as this would 
require adding across administrations.  

### Energy Can Transfer (ECT) Near and Far

`Progress.ect`
: Completion percentage for ECT posttest questionnaire

`Duration.ect`
: Length of time (in seconds) needed to complete ECT posttest questionnaire (including IMI and PA)

`Finished.ect`
: Did Qualtrics consider the ECT posttest questionnaire finished.

`RecordedDate.ect`
: Date ECT posttest questionnaire was collected

`A_NQ1.ect` through `A_NQ8.ect`
: Posttest responses to near transfer ECT questions, raw responses (Again in 
original text or ABC coding)

`A_FQ1.ect` through `A_FQ8.ect`
: Posttest responses to far transfer ECT questions, raw responses 
(Again in original text or ABC coding)

`SC0.ect`
: Posttest score as computed by Qualtrics

`A_NQ1_scored.ect` through `A_NQ8_scored.ect`
: Posttest scored (0,1) responses to near transfer ECT questions, scored responses

`A_FQ1_scored.ect` through `A_FQ8_scored.ect`
: Posttest scored (0,1) responses to far transfer ECT questions, scored responses

`NearECT.ect`, `FarECT.ect`, `ECT.ect`
: Sums of the scaled scores

### Properties of Torque (POT) Near and Far

`Progress.pot`
: Completion percentage for POT posttest questionnaire

`Duration.pot`
: Length of time (in seconds) needed to complete POT posttest questionnaire (including IMI and PA items)

`Finished.pot`
: Did Qualtrics consider the POT posttest questionnaire finished.

`RecordedData.pot`
: Date POT posttest questionnaire was collected

`A_NQ8.pot` through `A_NQ14.pot`
: POT posttest responses to near transfer POT questions, raw responses
(Again in original text or ABC coding)

`A_FQ8.pot` through `A_FQ14.pot`
: POT posttest responses to far transfer POT questions, raw responses
(Again in original text or ABC coding)

`SC0.pot`
: POT posttest score as computed by Qualtrics


`A-NQ8_scored.pot` through `A-NQ14_scored.pot`
: POT posttest scored (0,1) responses to near transfer POT questions, raw responses

`A-FQ8_scored.pot` through `A-FQ14_scored.pot`
: POT posttest scored (0,1) responses to far transfer POT questions, raw responses

`NearECT.ect`, `FarECT.ect`, `ECT.ect`
: Sums of the scaled scores

### Sum Scores

Precomputed sums of scored pretest/posttest items

Pretest sum scores:  `NearECT`, `FarECT`, `NearPOT`, `FarPOT`, `Near`, `Far`, `ECT`, `POT`, `PhysicsScore`

ECT posttest score: `NearECTpost`, `FarECTpost`, `ECTpost`

POT posttest score: `NearPOTpost`, `FarPOTpost`, `POTpost`

Posttest version of `Near`, `Far` and `PhysicsScores` are not precomputed as these 
require summing over tests given on different days. The following R code shows 
how to compute them if desired:

```{r NearFarPost}
#| eval: FALSE
Near.post <- NearECT.ect + NearPOT.pot
Far.post <- FarECT.ect + FarPOT.pot
Physics.post <- ECT.ect + POT.pot
```


## Intrinsic Motivation Inventory 

Here are [the questions](IMI.qmd)

The test was given once with the `ECT` posttest and the `POT` posttest.  Ones given
with the POT posttest have the suffix `.pot`.

`IMI_1` through `IMI_18` and `IMI_1.pot` through `IMI_18.pot`
: Item responses (reverse coded items reverse coded) with ECT (no prefix) or POT (`.pot`) posttest

`IMI`, `IMI.pot`
: Total score for IMI questionnaire

`IMI_Enj`, `IMI_Enj.pot`
: Enjoyment subscale

`IMI_Eng`, `IMI_Eng.pot`
: Engagement subscale

`IMI_PC`, `IMI_PC.pot`
: Player confidence subscale

`IMI_Effort`, `IMI_Effort.pot`
: Effort subscale

`IMI_Frust`, `IMI_Frust.pot`
: Frustration subscale

`IMI_Value`, `IMI_Value.pot`
: Value of experience subscale


## Physics Animation (Learning Support) Questionnaire

The questions are [here]

The test was given once with the `ECT` posttest and the `POT` posttest.  Ones given
with the POT posttest have the suffix `.pot`.

`PA_1` through `PA_7` and `PA_1.pot` through `PA_18.pot`
: Item responses (reverse coded items reverse coded) with ECT (no prefix) or POT (`.pot`) posttest

`PA`, `PA.pot`
: Total score for PA questionnaire

## Bayesian Network Scores

`context`
:

`timestamp`
:

The competencies in the [competency model](CompetencyModel.qmd) are 

* Root: `Physics` 
* High-level:  `Energy`, `Torque` (These correstpond to the ECT and POT tests)
* Low-level:  `NFL`, `NSL`, `NTL`, `POfMom`, `ConOfMom`, `EnergyTransfer`, `EnergyDissipate`, `StaticEquilibrium`, `PropertiesofTorque`

All variables can take on values of `High`, `Medium` and `Low`.  The Bayes net 
provides a posterior distribution over these values given the observed game outcomes.

In the definitions below `XXX` or $X$ should be replaced with one of the competencies. 

`XXX_EAP`
:This is the expected _a posteriori_ score, mapping `Low` = -1, `Medium` = 0 
and `High` = 1, 
$\textrm{EAP}(X)= -1\Pr(X=\textrm{Low}) + 0\Pr(X=\textrm{Medium}) + 1\Pr(X=\textrm{High})$.  
This value runs from 
$-1$ 
(very low) to $1$ (very high).

`XXX_Margin.High`, `XXX_Margin.Medium`, `XXX_Margin.Low`
:  Marginal distribution of `XXX`---$\PR(X=\textrm{High}$, $\PR(X=\textrm{Medium}$,
$\PR(X=\textrm{Low}$, respectively.  The three values should always add to $1$.


## Observables (Attempts and Results)

First and Last

Timestamps

Trophys

Attempts

## Learning Supports

Timestamps

Durations

Video lengths


